# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae129fecdcd7e3a7ecebb7f67b2047a0a9afe27b33a202490da53e5dc713ee4a245377b69cb136b2a24cb7740344cc4f6d74e6f86132c9e4389108c945b6a79

test:
  secret_key_base: 8d36f1ef4c3b6c809a7bf5313097f7364b4dc6fe9515f334f8a8ef6fa1208a1d55a59de28c5c3c98909a4ddfb92a788cf0da2ad50a8e396e5406b32762bd2292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
